version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "get-oppo-price"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1temhd0hp3eiy"
s3_prefix = "get-oppo-price"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
