AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless application, uses EventBridge schedules to trigger a lambda function to query oppo A96 price at Harvey Norman website, send message to SNS

Resources:
  # Define the SNS topic
  MySnsTopic:
    Type: AWS::SNS::Topic

  # Define the publisher Lambda function with permissions
  TopicPublisherFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 128
      Environment:
        Variables:
          SNStopic: !Ref MySnsTopic
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MySnsTopic.TopicName

  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: 'MySchedule'
      ScheduleExpression: 'cron(15 0 * * ? *)'
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt TopicPublisherFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn

  ScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ScheduleRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt TopicPublisherFunction.Arn

Outputs:
  TopicPublisherFunction:
    Description: TopicPublisherFunction function name
    Value: !Ref TopicPublisherFunction
  
  SNStopicName:
    Description: SNS topic name
    Value: !GetAtt MySnsTopic.TopicName

  SNStopicARN:
    Description: SNS topic ARN
    Value: !Ref MySnsTopic
